version: '3'
services:
  h4u:
    image: mophos/his-gateway:latest
    container_name: "his-gateway"
    volumes:
      - ./h4u-config:/home/h4u/h4u-api-his/h4u-config
    ports: 
      - 80:80
    restart: always
  watchtower:
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: watchtower his-gateway --interval 30
